### PR TITLE
fix for jspm

### PR DESCRIPTION
**Pull request by Hypercubed**
I believe this is good to merge.  It is a breaking change.

### CODE REVIEW

**Comment by Hypercubed** [comment]
This is the trouble with multiple modules.  We need to merge and publish this before we can finish credits-cli.

**Comment by stefanjudis** [comment]
@Hypercubed hmm... is it breaking? it was throwing before hand or?

**Comment by Hypercubed** [comment]
It is a breaking change.  This now outputs a hash with keys for each package  manager.  Just realized we need to update the readme as well.

**Comment by Hypercubed** [comment]
Or do you mean why the try-catch?  Because not every module has a package.json.

**Comment by Hypercubed** [comment]
Perhaps not clear that this is a PR against the 3-support-different-package-managers branch, which also needs to be merged into master.

**Comment by stefanjudis** [comment]
> Perhaps not clear that this is a PR against the 3-support-different-package-managers branch, which also needs to be merged into master.

Hah! Here we go... :D

Does the support for different managers have a 👍 from your side? Then I'd trust you on that one. :)

**Pull request merged**
