### PR TITLE
Polyfilling promises

### LINKED ISSUE #1: Promise is not defined
Found when using credits-cli

screen shot 2015-10-26 at 00 58 48

### PR DESCRIPTION
**Pull request by adam-lynch**
Fixes #1

### CODE REVIEW

**Comment by adam-lynch** [comment]
Tested with credits-cli and it works for me now.

**Comment by stefanjudis** [comment]
Is there maybe something smaller than bluebird? 
Bluebird is a heavy flagship and we wouldn't use 95% of it.

**Comment by adam-lynch** [comment]
Not sure tbh. All I know it's good and recommended by everyone (& better than Q which I've used before). Maybe someone else can weigh in.

**Comment by stefanjudis** [comment]
Jap, true - bluebird is great! But if offers also a ton of additional functionality, which we don't need for now.

What about this one?

https://github.com/jakearchibald/es6-promise

That's really only a polyfill. :)

**Comment by adam-lynch** [comment]
Sure, I can throw that in if you like.

Regards,
Adam Lynch

**Comment by stefanjudis** [comment]
Resolved with https://github.com/stefanjudis/credits/commit/dd0932fdde1d1238395cfa44a17647f2850dcb94.

**Comment by adam-lynch** [comment]
Woops sorry I forgot.

**Comment by stefanjudis** [comment]
No problem... Quick check that it's fixed would be nice though. It's running smoothly here. :)

**Comment by adam-lynch** [comment]
Took me awhile because I managed to install a version of Xcode which was incompatible with my OS version and it somehow made `npm install`s fail.  Works fine now :smile:

**Comment by stefanjudis** [comment]
Nice. Thanks again for reporting. :)

**Pull request closed without merging**
